### ISSUE TITLE
Question about pyEcoHAB

### ISSUE THREAD

**Issue by xusurui** [Neuroinflab/pyEcoHAB#53]
hello! could you tell me the meaning of the event in the fifth column of data? The detail site is below.
(pyEcoHAB/data/BALB_VPA_data_cohort_1/20140616_120000.txt)

**Comment by asiaszmek** [comment]
It's the duration of tag registration by the antenna (in microsecond).

**Comment by xusurui** [comment]
oh, thank you. And do you have Eco-HAB.rfid – software package?

**Comment by asiaszmek** [comment]
Unfortunately not. You should contact the authors of https://elifesciences.org/articles/19532

**Comment by asiaszmek** [comment]
I am happy to help with the actual behavioral data analysis, reading in data, etc, but setting up Eco-HAB is not my area of expertise.

**Comment by xusurui** [comment]
ｏｋ，ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ！

**Comment by xusurui** [comment]
Hello, do you konw how to calculate the duration of tag registration by the antenna (in microsecond)?
I'm confused about the meaning of tag and antenna, for example, the duration is the same one tag in the same one antenna, or one tag go through two adjacent antenna. 
I emailed the author, but they haven't replied yet.
