### ISSUE TITLE
Question about  "the duration of tag registration by the antenna"

### ISSUE THREAD

**Issue by xusurui** [Neuroinflab/pyEcoHAB#54]
Hello, do you konw how to calculate the duration of tag registration by the antenna (in microsecond)?
I'm confused about the meaning of tag and antenna, for example, the duration is the same one tag in the same one antenna, or one tag go through two adjacent antenna.

**Comment by asiaszmek** [comment]
Hello,
The Eco-HAB system is an automatic device (build from compartments that are connected by tunnels) for experiments investigating social behavior of animals. Each animal has a RFID-tag (the tag), which is registered by antennas that are placed in the Eco-HAB system (at the entrances to tunnels), when an animal is close to an antenna. I am not sure, but I suspect that if the registration duration is shorter than 50 us (the antenna is registering the tag for less than 50 us), this registration is discarded.
I think that there is some confusion with "duration". pyEcoHAB has an algorithm to establish, when an animal visited a compartment and calculates visit duration (interval between registration of the tag by two consecutive antennas). Hence Loader provides two methods: get_duration() for registration duration (in us) and get_visit_duration() for duration of the visit (in ms).

**Comment by xusurui** [comment]
Thank you for answering my question, you are so nice. 
I've received some data, registered  by antenna, that are saved in seperate txt file from different antenna, and this data in each txt need to be merged together and ranked by time. Are yours like this?
I've uploaded some of my data in below site, could you look at them and show me how to calculate the duration of tag registration by the antenna?
(https://github.com/xusurui/Eco-Hab-for-learn-and-test/tree/main/data%20for%20test)
