### ISSUE TITLE
setup file in the sample data

### ISSUE THREAD

**Issue by sborrie** [Neuroinflab/pyEcoHAB#59]
I was testing the sample data that is included in the package now, and I noticed that the folder 'BALB_VPA_data_cohort_1' doesn't have a setup.txt file. 
When running the code, the message 'No setup config found in...' was being displayed. It was resulting in the output data not being divided into the 4 compartments ie outputting everything as being from cage A. 
I could fix this now by copying the default setup file into the folder location (which I hope was the correct setup for the sample data!), and now the data looks as it should. But maybe you want to fix this for future users. 
Thanks!

**Comment by asiaszmek** [comment]
pyEcoHAB includes a setup file for a EcoHAB standard experiment, so you do not need to include it with the data files. The warning "no setup found in ...." means just that.  I should probably add a message about loading standard setup instead. 

At what behavioral variable were you looking, when you stated that: " It was resulting in the output data not being divided into the 4 compartments ie outputting everything as being from cage A"?  
I ran the example on my computer and I the activity was divided correctly to all the cages. Were you looking at incohort_sociability? Incohort sociability is defined and calculated as a variable for the whole time interval, so indeed data from all the cages gets dumped into one number and it's not a bug it's a feature.

Could you show me the code you used?

Thanks!

**Comment by sborrie** [comment]
Ah OK, that makes sense now. So it will always use the default if there is no setup. I looked back at the those output files now and the data is in fact divided across the different cages, I must have missed it in the file i checked since there was so much data. Sorry!
